//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MAKM { get; set; }
        public string TENKM { get; set; }
        public Nullable<double> PHAMTRAM { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
