//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public string MAKM { get; set; }
        public string TENKM { get; set; }
        public Nullable<int> MASP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
